version: '3.3'
services:
  db:
    image: library/postgres:12.3
    container_name: postgres-dev
    hostname: postgres-dev
    ports:
      - "127.0.0.1:8885:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./dev/:/docker-entrypoint-initdb.d/
